package Tuotehaku.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import Tuotehaku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 01:37:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KaupatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa37 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa37() throws SailoException {    // Kaupat: 37
    Kaupat kaupat = new Kaupat(); 
    Kauppa a = new Kauppa(), b = new Kauppa(); 
    assertEquals("From: Kaupat line: 41", 0, kaupat.getLkm()); 
    kaupat.lisaa(a); assertEquals("From: Kaupat line: 42", 1, kaupat.getLkm()); 
    kaupat.lisaa(b); assertEquals("From: Kaupat line: 43", 2, kaupat.getLkm()); 
    assertEquals("From: Kaupat line: 44", a, kaupat.anna(0)); 
    assertEquals("From: Kaupat line: 45", b, kaupat.anna(1)); 
    assertEquals("From: Kaupat line: 46", false, kaupat.anna(1) == a); 
    assertEquals("From: Kaupat line: 47", false, kaupat.anna(0) == b); 
    try {
    assertEquals("From: Kaupat line: 48", a, kaupat.anna(2)); 
    fail("Kaupat: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kaupat.lisaa(a); assertEquals("From: Kaupat line: 49", 3, kaupat.getLkm()); 
    kaupat.lisaa(b); assertEquals("From: Kaupat line: 50", 4, kaupat.getLkm()); 
    kaupat.poista(7); assertEquals("From: Kaupat line: 51", 3, kaupat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta111 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta111() throws SailoException {    // Kaupat: 111
    Kaupat kaupat = new Kaupat(); 
    Kauppa a = new Kauppa(), b = new Kauppa(); 
    a.vastaaXXL(); b.vastaaXXL(); 
    kaupat.lisaa(a); 
    kaupat.lisaa(b); 
    kaupat.tallenna(); 
    kaupat = new Kaupat(); 
    kaupat.lueTiedostosta("kaupat.dat"); 
    kaupat.lisaa(b); 
    kaupat.tallenna(); 
  } // Generated by ComTest END
}