package Tuotehaku.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Tuotehaku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 01:37:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi28 */
  @Test
  public void testGetNimi28() {    // Kauppa: 28
    Kauppa XXL = new Kauppa(); 
    XXL.vastaaXXL(); 
    assertEquals("From: Kauppa line: 31", "XXL", XXL.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi151 */
  @Test
  public void testRekisteroi151() {    // Kauppa: 151
    Kauppa a = new Kauppa(); 
    assertEquals("From: Kauppa line: 153", 0, a.getTunnusNro()); 
    a.rekisteroi(); 
    Kauppa b = new Kauppa(); 
    b.rekisteroi(); 
    int n1 = a.getTunnusNro(); 
    int n2 = b.getTunnusNro(); 
    assertEquals("From: Kauppa line: 159", n2-1, n1); 
  } // Generated by ComTest END
}