package Tuotehaku.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.*;
import Tuotehaku.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 01:37:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuotteetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta57 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta57() throws SailoException {    // Tuotteet: 57
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote tuote1 = new Tuote(); tuote1.parse("1|Harry Potter & Viisaasten Kivi|19.95|4.7"); 
    Tuote tuote2 = new Tuote(); tuote2.parse("1|Fingerpori 14|17.95|3.3"); 
    Tuote tuote3 = new Tuote(); tuote3.parse("1|Suuri ristikkokirja|4.95|2.7"); 
    Tuote tuote4 = new Tuote(); tuote4.parse("2|OnePlus Nord 5G älypuhelin|399.0|4.6"); 
    tuotteet.lueTiedostosta("tuotteet.dat"); 
    Iterator<Tuote> i = tuotteet.iterator(); 
    assertEquals("From: Tuotteet line: 67", "1|Harry Potter & Viisaasten Kivi|19.95|4.7", i.next().toString()); 
    assertEquals("From: Tuotteet line: 68", "1|Fingerpori 14|17.95|3.3", i.next().toString()); 
    assertEquals("From: Tuotteet line: 69", "1|Suuri ristikkokirja|4.95|2.7", i.next().toString()); 
    assertEquals("From: Tuotteet line: 70", "2|OnePlus Nord 5G älypuhelin|399.0|4.6", i.next().toString()); 
    assertEquals("From: Tuotteet line: 71", true, i.hasNext()); 
    tuotteet.lisaa(tuote4); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm152 */
  @Test
  public void testGetLkm152() {    // Tuotteet: 152
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote imuri = new Tuote("imuri",79,3,2); 
    Tuote limu = new Tuote("limu",2,4,2); 
    assertEquals("From: Tuotteet line: 157", 0, tuotteet.getLkm()); 
    tuotteet.lisaa(imuri); 
    tuotteet.lisaa(limu); 
    assertEquals("From: Tuotteet line: 160", 2, tuotteet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator170 */
  @Test
  public void testIterator170() {    // Tuotteet: 170
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote tuote1 = new Tuote(); tuote1.parse("1|Harry Potter & Viisaasten Kivi|19.95|4.7"); 
    Tuote tuote2 = new Tuote(); tuote2.parse("1|Fingerpori 14|17.95|3.3"); 
    Tuote tuote3 = new Tuote(); tuote3.parse("1|Suuri ristikkokirja|4.95|2.7"); 
    Tuote tuote4 = new Tuote(); tuote4.parse("2|OnePlus Nord 5G älypuhelin|399.0|4.6"); 
    int j = 0; 
    for (Tuote tuote : tuotteet)
    {
    assertEquals("From: Tuotteet line: 181", 1, tuote.getKauppaid()); 
    j++; 
    if (j > 3) break; 
    }
  } // Generated by ComTest END
}